LongName: University of South Florida
Description: The University of South Florida

ID: 10251

AddressLine1: 4202 E Fowler Ave
City: Tampa

Country: US
State: Florida
Zipcode: "33620"

Latitude: 28.058893
Longitude: -82.412738
