LongName: University of Chicago VC3
Description: The University of Chicago VC3 virtual cluster 

ID: 10249

AddressLine1: 5801 S Ellis Ave
City: Chicago

Country: US
State: Ilinois
Zipcode: "60637"

Latitude: 45
Longitude: -90
