# LongName is the expanded name of the site
LongName: Brookhaven National Labs OSG infrastructure
# Description is a brief description of your site
Description: Brookhaven National Labs OSG infrastructure

# If you have an up-to-date local git clone, fill ID with the output from `bin/next_site_id`
# Otherwise, leave it blank and we will fill in the appropriate value for you.
ID: 10247

# AddressLine1 is the street address of the site
AddressLine1: 98 Rochester St
### AddressLine2 (optional) is the second line of the street address
# AddressLine2: Room 101
# City is the city the site is located in
City: Upton

# Country is the country the site is located in
Country: USA
### State (optional) is the state or province the site is located in
State: New York
### Zipcode (optional) is the zipcode/postal code of the site
Zipcode: "11973"

# Latitude is the latitude of the site (positive values are in the northern hemisphere)
Latitude: 40.8642675
# Longitude is the longitude of the site (positive values are in the eastern hemisphere)
Longitude: -72.8773571

